name: CI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: yarn install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Release
      run: yarn release
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
